apiVersion: v1
items:
- apiVersion: neuvector.com/v1
  kind: NvSecurityRule
  metadata:
    creationTimestamp: null
    name: nv.nginx-deployment.gitops
    namespace: gitops
  spec:
    dlp:
      settings: []
      status: true
    egress: []
    file: []
    ingress:
    - action: allow
      applications:
      - HTTP
      name: nv.nginx-deployment.gitops-ingress-0
      ports: any
      priority: 0
      selector:
        comment: ""
        criteria: []
        name: nodes
        original_name: ""
    - action: allow
      applications:
      - HTTP
      name: nv.nginx-deployment.gitops-ingress-1
      ports: any
      priority: 0
      selector:
        comment: ""
        name: Workload:ingress
        original_name: ""
    process:
    - action: allow
      allow_update: false
      name: nginx
      path: /usr/sbin/nginx
    - action: allow
      allow_update: false
      name: pause
      path: /pause
    process_profile:
      baseline: zero-drift
      mode: Discover
    target:
      policymode: Discover
      selector:
        comment: ""
        criteria:
        - key: service
          op: =
          value: nginx-deployment.gitops
        - key: domain
          op: =
          value: gitops
        grp_band_width: 0
        grp_sess_cur: 0
        grp_sess_rate: 0
        mon_metric: false
        name: nv.nginx-deployment.gitops
        original_name: ""
    waf:
      settings: []
      status: true
kind: List
metadata: {}
