apiVersion: v1
items:
- apiVersion: neuvector.com/v1
  kind: NvSecurityRule
  metadata:
    name: nv.nginx-deployment.gitops
    namespace: gitops
  spec:
    dlp:
      settings: []
      status: true
    egress:
    - action: allow
      applications:
      - SSL
      name: external-egress-0
      ports: any
      priority: 0
      selector:
        comment: ""
        criteria: []
        name: external
        original_name: ""
    - action: allow
      applications:
      - DNS
      name: nv.rke2-coredns-rke2-coredns.kube-system-egress-1
      ports: any
      priority: 0
      selector:
        comment: ""
        criteria:
        - key: service
          op: =
          value: rke2-coredns-rke2-coredns.kube-system
        - key: domain
          op: =
          value: kube-system
        name: nv.rke2-coredns-rke2-coredns.kube-system
        original_name: ""
    file: []
    ingress:
    - action: allow
      applications:
      - HTTP
      name: nv.nginx-deployment.gitops-ingress-0
      ports: any
      priority: 0
      selector:
        comment: ""
        criteria: []
        name: nodes
        original_name: ""
    - action: allow
      applications:
      - HTTP
      name: nv.nginx-deployment.gitops-ingress-1
      ports: any
      priority: 0
      selector:
        comment: ""
        criteria:
        - key: service
          op: =
          value: rke2-ingress-nginx-controller.kube-system
        - key: domain
          op: =
          value: kube-system
        name: nv.rke2-ingress-nginx-controller.kube-system
        original_name: ""
    process:
    - action: allow
      allow_update: false
      name: nginx
      path: /usr/sbin/nginx
    - action: allow
      allow_update: false
      name: pause
      path: /pause
    process_profile:
      baseline: zero-drift
    target:
      policymode: Protect
      selector:
        comment: ""
        criteria:
        - key: service
          op: =
          value: nginx-deployment.gitops
        - key: domain
          op: =
          value: gitops
        name: nv.nginx-deployment.gitops
        original_name: ""
    waf:
      settings: []
      status: true
kind: List
metadata: null
