apiVersion: v1
items:
- apiVersion: neuvector.com/v1
  kind: NvSecurityRule
  metadata:
    creationTimestamp: null
    name: nv.nginx-deployment.gitops
    namespace: gitops
  spec:
    dlp:
      settings: []
      status: true
    egress: []
    file: []
    ingress: []
    process:
    - action: allow
      allow_update: false
      name: awk
      path: /usr/bin/mawk
    - action: allow
      allow_update: false
      name: basename
      path: /usr/bin/basename
    - action: allow
      allow_update: false
      name: cut
      path: /usr/bin/cut
    - action: allow
      allow_update: false
      name: dash
      path: /usr/bin/dash
    - action: allow
      allow_update: false
      name: dpkg-query
      path: /usr/bin/dpkg-query
    - action: allow
      allow_update: false
      name: find
      path: /usr/bin/find
    - action: allow
      allow_update: false
      name: grep
      path: /usr/bin/grep
    - action: allow
      allow_update: false
      name: md5sum
      path: /usr/bin/md5sum
    - action: allow
      allow_update: false
      name: nginx
      path: /usr/sbin/nginx
    - action: allow
      allow_update: false
      name: pause
      path: /pause
    - action: allow
      allow_update: false
      name: sed
      path: /usr/bin/sed
    - action: allow
      allow_update: false
      name: sh
      path: /usr/bin/dash
    - action: allow
      allow_update: false
      name: sort
      path: /usr/bin/sort
    - action: allow
      allow_update: false
      name: touch
      path: /usr/bin/touch
    process_profile:
      baseline: zero-drift
      mode: Protect
    target:
      policymode: Protect
      selector:
        comment: ""
        criteria:
        - key: service
          op: =
          value: nginx-deployment.gitops
        - key: domain
          op: =
          value: gitops
        grp_band_width: 0
        grp_sess_cur: 0
        grp_sess_rate: 0
        mon_metric: false
        name: nv.nginx-deployment.gitops
        original_name: ""
    waf:
      settings: []
      status: true
kind: List
metadata: {}
