apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: gitops
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
        - name: nginx-htmls
          configMap:
            name: cm-nginx-htmls
      containers:
      - name: nginx
        image: nginx:latest
        volumeMounts:
          - name: nginx-htmls
            mountPath: /usr/share/nginx/html
        ports:
        - containerPort: 80

