apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gitops
#configMapGenerator:
#- name: cm-nginx-htmls
#  files:
#  - ./index.html
#  - ./50x.html

resources:
  - ./deployment.yaml
  - ./service.yaml
  - ./namespace.yaml
