apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
- files:
  - nginx-htmls/index.html
  - nginx-htmls/50x.html
  name: nginx-htmls

resources:
  - deployment.yaml
  - service.yaml
  - namespace.yaml
